import Link from "next/link";
import { notFound } from "next/navigation";
import { deletePropertyAction } from "@/app/_actions/foundation";
import { ConfirmSubmitButton } from "@/components/forms/confirm-submit-button";
import { PlacePreview } from "@/components/maps/place-preview";
import { PropertyGallery } from "@/components/maps/property-gallery";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { getSystemUser, WRITE_ROLES } from "@/lib/auth/authorization";
import { formatCurrency } from "@/lib/format";
import { obtenerPropiedad } from "@/lib/services/foundation";

const typeLabels = { DEPARTAMENTO: "Departamento", LOCAL_COMERCIAL: "Local comercial", ACCESORIA: "Accesoria", BODEGA: "Bodega", OFICINA: "Oficina", OTRO: "Otro" } as const;

export default async function PropertyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [{ user }, property] = await Promise.all([getSystemUser(), obtenerPropiedad(id)]); if (!property) notFound();
  const canWrite = WRITE_ROLES.includes(user.rol as (typeof WRITE_ROLES)[number]); const latitude = property.latitud ? Number(property.latitud) : null; const longitude = property.longitud ? Number(property.longitud) : null;
  const stats = [["Valor catastral", formatCurrency(property.valorCatastral), null], ["Valor comercial", formatCurrency(property.valorComercialTotal), null], ["Predial anual", formatCurrency(property.predialAnual), `Equivale a ${formatCurrency(Number(property.predialAnual) / 12)} al mes`], ["Mantenimiento anual", formatCurrency(property.mantenimientoAnual), `Equivale a ${formatCurrency(Number(property.mantenimientoAnual) / 12)} al mes`]];
  return <><PageHeader action={canWrite ? <Link className="inline-flex rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white" href={`/propiedades/${id}/editar`}>Editar propiedad</Link> : null} description="Ficha general, galería, ubicación y espacios rentables." eyebrow="Propiedad" title={property.direccion} />
    <section className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,0.9fr)_minmax(420px,1.1fr)]"><div><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand text-sm font-bold text-white">{property.propietario.nombre.charAt(0).toUpperCase()}</span><div><p className="text-xs font-bold uppercase tracking-[.1em] text-ink-secondary">Propietario</p><h2 className="font-serif text-xl font-semibold text-ink">{property.propietario.nombre}</h2></div></div><h3 className="mt-7 font-serif text-xl font-semibold text-ink">Información financiera</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{stats.map(([label, amount, detail]) => <div className="rounded-2xl bg-bg p-5 shadow-[5px_5px_12px_#c6cdd6,-5px_-5px_12px_#fff]" key={label}><p className="text-xs font-bold uppercase tracking-[.1em] text-ink-secondary">{label}</p><p className="mt-2 text-xl font-bold text-brand [font-variant-numeric:tabular-nums]">{amount}</p>{detail ? <p className="mt-2 text-xs text-ink-secondary">{detail}</p> : null}</div>)}</div></div><div className="space-y-6"><div><h2 className="mb-4 font-serif text-xl font-semibold text-ink">Galería</h2><PropertyGallery photos={property.archivos} title={property.direccion} /></div>{latitude !== null && longitude !== null ? <div><h2 className="mb-4 font-serif text-xl font-semibold text-ink">Ubicación</h2><PlacePreview address={property.direccion} latitude={latitude} longitude={longitude} /></div> : null}</div></section>
    <section className="mt-10"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-2xl font-semibold text-ink">Unidades</h2><p className="mt-1 text-sm text-ink-secondary">Espacios rentables dentro del inmueble.</p></div>{canWrite ? <Link className="rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white" href={`/propiedades/${id}/unidades/nueva`}>Nueva unidad</Link> : null}</div>{property.unidades.length === 0 ? <EmptyState description="Agrega el primer espacio rentable dentro de este predio." title="Sin unidades registradas" /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{property.unidades.map((unit) => <Link className="rounded-2xl bg-bg p-5 shadow-[5px_5px_12px_#c6cdd6,-5px_-5px_12px_#fff]" href={`/propiedades/${id}/unidades/${unit.id}`} key={unit.id}><p className="text-xs font-bold uppercase tracking-[.1em] text-brand">{typeLabels[unit.tipo]}</p><h3 className="mt-2 text-lg font-bold text-ink">Unidad {unit.identificador}</h3><p className="mt-2 text-sm text-ink-secondary">{unit.metrosCuadrados.toString()} m² · {unit.recamaras} recámaras · {unit.banosCompletos} baños</p></Link>)}</div>}</section>{canWrite && property.unidades.length === 0 ? <section className="mt-8 border-t border-border pt-5"><form action={deletePropertyAction.bind(null, id)}><ConfirmSubmitButton message="¿Eliminar esta propiedad? Esta acción no se puede deshacer.">Eliminar propiedad</ConfirmSubmitButton></form></section> : null}</>;
}
