import Link from "next/link";
import { notFound } from "next/navigation";
import { deletePropertyAction } from "@/app/_actions/foundation";
import { ConfirmSubmitButton } from "@/components/forms/confirm-submit-button";
import { PlacePreview } from "@/components/maps/place-preview";
import { PropertyGallery } from "@/components/maps/property-gallery";
import { Alert } from "@/components/ui/alert";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { getSystemUser, WRITE_ROLES } from "@/lib/auth/authorization";
import { formatCurrency } from "@/lib/format";
import { obtenerPropiedad } from "@/lib/services/foundation";

const typeLabels = { DEPARTAMENTO: "Departamento", LOCAL_COMERCIAL: "Local comercial", ACCESORIA: "Accesoria", BODEGA: "Bodega", OFICINA: "Oficina", OTRO: "Otro" } as const;

export default async function PropertyDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ aviso?: string }> }) {
  const { id } = await params; const query = await searchParams; const [{ user }, property] = await Promise.all([getSystemUser(), obtenerPropiedad(id)]); if (!property) notFound();
  const canWrite = WRITE_ROLES.includes(user.rol as (typeof WRITE_ROLES)[number]); const latitude = property.latitud ? Number(property.latitud) : null; const longitude = property.longitud ? Number(property.longitud) : null;
  const stats = [["Valor catastral", formatCurrency(property.valorCatastral), null], ["Valor comercial", formatCurrency(property.valorComercialTotal), null], ["Predial anual", formatCurrency(property.predialAnual), `Equivale a ${formatCurrency(Number(property.predialAnual) / 12)} al mes`], ["Mantenimiento anual", formatCurrency(property.mantenimientoAnual), `Equivale a ${formatCurrency(Number(property.mantenimientoAnual) / 12)} al mes`]];
  return <><PageHeader action={canWrite ? <Link className="inline-flex rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white shadow-[4px_4px_9px_#b8c2cd] hover:bg-brand-hover" href={`/propiedades/${id}/editar`}>Editar propiedad</Link> : null} description="Resumen financiero, espacios disponibles, galería y ubicación del inmueble." eyebrow="Ficha de propiedad" title={property.direccion} />
    {query.aviso ? <Alert className="mt-6" variant="warning">{query.aviso}</Alert> : null}
    <section className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]"><div><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-xl font-semibold text-ink">Galería del inmueble</h2><p className="mt-1 text-sm text-ink-secondary">Imágenes registradas de esta propiedad</p></div><span className="rounded-full bg-brand/8 px-3 py-1.5 text-xs font-bold text-brand">{property.archivos.length} {property.archivos.length === 1 ? "foto" : "fotos"}</span></div><PropertyGallery photos={property.archivos} title={property.direccion} /></div>
      <aside className="self-start rounded-3xl bg-bg p-6 shadow-[8px_8px_18px_#c6cdd6,-8px_-8px_18px_#fff] xl:sticky xl:top-6"><div className="flex items-center gap-3 border-b border-brand/10 pb-5"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand text-base font-bold text-white">{property.propietario.nombre.charAt(0).toUpperCase()}</span><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-ink-secondary">Propietario</p><h2 className="font-serif text-xl font-semibold text-ink">{property.propietario.nombre}</h2></div></div><div className="mt-5 flex items-center justify-between rounded-2xl bg-brand px-4 py-3 text-white"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-white/70">Espacios rentables</p><p className="mt-1 text-sm font-semibold">Unidades del inmueble</p></div><span className="text-3xl font-bold [font-variant-numeric:tabular-nums]">{property.unidades.length}</span></div><div className="mt-6 flex items-baseline justify-between"><h2 className="font-serif text-xl font-semibold text-ink">Resumen financiero</h2><span className="text-xs text-ink-secondary">Importes anuales</span></div><dl className="mt-3 grid grid-cols-2 overflow-hidden rounded-2xl border border-brand/10">{stats.map(([label, amount, detail], index) => <div className={`min-w-0 p-4 ${index % 2 === 0 ? "border-r border-brand/10" : ""} ${index > 1 ? "border-t border-brand/10" : ""}`} key={label}><dt className="text-[10px] font-bold uppercase tracking-[.08em] text-ink-secondary">{label}</dt><dd className="mt-1 truncate text-base font-bold text-brand [font-variant-numeric:tabular-nums]" title={amount ?? undefined}>{amount}</dd>{detail ? <p className="mt-1 line-clamp-2 text-[11px] leading-relaxed text-ink-secondary">{detail}</p> : null}</div>)}</dl></aside>
    </section>
    {latitude !== null && longitude !== null ? <section className="mt-10"><div className="mb-4 flex items-end justify-between gap-4"><div><h2 className="font-serif text-2xl font-semibold text-ink">Ubicación</h2><p className="mt-1 text-sm text-ink-secondary">Consulta el punto registrado para este inmueble.</p></div><span className="hidden rounded-full bg-brand/8 px-3 py-1.5 text-xs font-bold text-brand sm:block">Ubicación verificada</span></div><div className="max-w-5xl"><PlacePreview address={property.direccion} latitude={latitude} longitude={longitude} /></div></section> : null}
    <section className="mt-10"><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-brand/70">Inventario rentable</p><h2 className="mt-1 font-serif text-2xl font-semibold text-ink">Unidades</h2><p className="mt-1 text-sm text-ink-secondary">{property.unidades.length === 0 ? "Aún no hay espacios registrados." : `${property.unidades.length} ${property.unidades.length === 1 ? "espacio registrado" : "espacios registrados"} en este inmueble.`}</p></div>{canWrite ? <Link className="inline-flex w-fit rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white shadow-[4px_4px_9px_#b8c2cd] hover:bg-brand-hover" href={`/propiedades/${id}/unidades/nueva`}>Nueva unidad</Link> : null}</div>{property.unidades.length === 0 ? <EmptyState description="Agrega el primer espacio rentable dentro de este predio." title="Sin unidades registradas" /> : <div className="grid gap-4 md:grid-cols-2">{property.unidades.map((unit) => <Link className="group flex items-center justify-between gap-4 rounded-2xl bg-bg p-5 shadow-[5px_5px_12px_#c6cdd6,-5px_-5px_12px_#fff] transition hover:-translate-y-0.5" href={`/propiedades/${id}/unidades/${unit.id}`} key={unit.id}><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-brand">{typeLabels[unit.tipo]}</p><h3 className="mt-1 text-lg font-bold text-ink group-hover:text-brand">Unidad {unit.identificador}</h3><p className="mt-2 text-sm text-ink-secondary">{unit.metrosCuadrados.toString()} m² <span aria-hidden="true">·</span> {unit.recamaras} recámaras <span aria-hidden="true">·</span> {unit.banosCompletos} baños</p></div><span aria-hidden="true" className="shrink-0 text-xl font-bold text-brand">→</span></Link>)}</div>}</section>{canWrite && property.unidades.length === 0 ? <section className="mt-8 border-t border-border pt-5"><form action={deletePropertyAction.bind(null, id)}><ConfirmSubmitButton message="¿Eliminar esta propiedad? Esta acción no se puede deshacer.">Eliminar propiedad</ConfirmSubmitButton></form></section> : null}</>;
}
