import { Alert } from "@/components/ui/alert";
import { PageHeader } from "@/components/ui/page-header";
import { getSystemUser, WRITE_ROLES } from "@/lib/auth/authorization";
import { formatPercent } from "@/lib/format";
import { listarIndicesInflacion, obtenerReporteInflacion } from "@/lib/services/inflation";

export default async function InflationPage({ searchParams }: { searchParams: Promise<{ anio?: string; guardado?: string; error?: string }> }) {
  const query = await searchParams;
  const year = Number(query.anio) || new Date().getFullYear();
  const [{ user }, indices, report] = await Promise.all([getSystemUser(), listarIndicesInflacion(), obtenerReporteInflacion(year)]);
  const canWrite = WRITE_ROLES.includes(user.rol as (typeof WRITE_ROLES)[number]);
  const nowMonth = new Date().toISOString().slice(0, 7);
  return <>
    <PageHeader eyebrow="Inflación y renovación" title="Índice Nacional de Precios" description="Captura niveles oficiales del INPC con corte fijo al día 10 y consulta su variación anual." />
    {query.guardado ? <Alert className="mt-7" variant="success">Nivel INPC guardado correctamente.</Alert> : null}
    {query.error ? <Alert className="mt-7" variant="danger">{query.error}</Alert> : null}
    {canWrite ? <section className="mt-7 rounded-card border border-border bg-surface p-5"><h2 className="text-sm font-semibold text-ink">Capturar nivel oficial</h2><form action="/api/inflacion/indices" className="mt-5 grid gap-4 sm:grid-cols-4" method="post"><input name="indice" type="hidden" value="INPC" /><label className="text-xs font-medium text-ink-secondary">Mes<input className="mt-2 w-full rounded border border-border bg-surface px-3 py-2.5 text-sm text-ink" defaultValue={nowMonth} name="mes" required type="month" /></label><label className="text-xs font-medium text-ink-secondary">Nivel oficial<input className="mt-2 w-full rounded border border-border bg-surface px-3 py-2.5 text-sm text-ink" name="valor" placeholder="140.78000000" required inputMode="decimal" /></label><label className="text-xs font-medium text-ink-secondary">Fecha de corte<input className="mt-2 w-full rounded border border-border bg-surface px-3 py-2.5 text-sm text-ink" defaultValue={`${nowMonth}-10`} name="fechaCorte" required type="date" /></label><div className="flex items-end"><button className="w-full rounded bg-brand px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-hover" type="submit">Guardar índice</button></div></form></section> : null}
    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-sm font-semibold text-ink">Reporte anual</h2><p className="mt-1 text-xs text-ink-secondary">El acumulado compara diciembre anterior contra el último nivel disponible del año.</p></div><div className="flex items-center gap-2"><form><input className="rounded border border-border bg-surface px-3 py-2 text-sm text-ink" defaultValue={year} max="2200" min="1900" name="anio" type="number" /><button className="ml-2 rounded border border-border bg-surface px-4 py-2 text-sm font-semibold text-ink hover:bg-bg">Consultar</button></form><a className="rounded bg-brand px-4 py-2 text-sm font-semibold text-white hover:bg-brand-hover" href={`/api/inflacion/reporte?anio=${year}`}>Exportar CSV</a></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-card border border-border bg-surface p-5"><p className="text-xs font-medium text-ink-secondary">Inflación acumulada {year}</p><p className="mt-2 text-2xl font-bold tracking-tight text-brand [font-variant-numeric:tabular-nums]">{report.acumulado === null ? "Incompleto" : formatPercent(report.acumulado * 100)}</p></div><div className="rounded-card border border-border bg-surface p-5"><p className="text-xs font-medium text-ink-secondary">Niveles capturados</p><p className="mt-2 text-2xl font-bold tracking-tight text-brand [font-variant-numeric:tabular-nums]">{report.meses.length} / 12</p></div></div></section>
    <section className="mt-7 overflow-x-auto rounded-card border border-border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs font-semibold uppercase tracking-wide text-ink-secondary"><tr><th className="px-5 py-3">Mes</th><th className="px-5 py-3">Índice</th><th className="px-5 py-3 text-right">Nivel oficial</th><th className="px-5 py-3">Corte</th></tr></thead><tbody className="divide-y divide-border">{indices.map((item) => <tr className="hover:bg-bg/50" key={item.id}><td className="px-5 py-4">{item.mes.toISOString().slice(0, 7)}</td><td className="px-5 py-4 text-ink-secondary">{item.indice}</td><td className="px-5 py-4 text-right font-semibold [font-variant-numeric:tabular-nums]">{item.valor.toString()}</td><td className="px-5 py-4 text-ink-secondary">{item.fechaCorte.toISOString().slice(0, 10)}</td></tr>)}</tbody></table></section>
  </>;
}
