import { Alert } from "@/components/ui/alert";
import { PageHeader } from "@/components/ui/page-header";
import { getSystemUser, WRITE_ROLES } from "@/lib/auth/authorization";
import { formatPercent } from "@/lib/format";
import { obtenerSugerenciaInpc } from "@/lib/services/banxico";
import { listarIndicesInflacion, obtenerReporteInflacion } from "@/lib/services/inflation";

const cp154Url = "https://www.banxico.org.mx/SieInternet/consultarDirectorioInternetAction.do?sector=8&accion=consultarCuadro&idCuadro=CP154&locale=es";
const cp151Url = "https://www.banxico.org.mx/SieInternet/consultarDirectorioInternetAction.do?sector=8&accion=consultarCuadro&idCuadro=CP151&locale=es";

export default async function InflationPage({ searchParams }: { searchParams: Promise<{ anio?: string; guardado?: string; error?: string; mes?: string; valor?: string }> }) {
  const query = await searchParams;
  const year = Number(query.anio) || new Date().getFullYear();
  const [{ user }, indices, report, suggestion] = await Promise.all([getSystemUser(), listarIndicesInflacion(), obtenerReporteInflacion(year), obtenerSugerenciaInpc()]);
  const canWrite = WRITE_ROLES.includes(user.rol as (typeof WRITE_ROLES)[number]);
  const selectedMonth = query.mes ?? new Date().toISOString().slice(0, 7);

  return <>
    <PageHeader description="Consulta la fuente oficial, registra el nivel mensual y revisa el avance anual." eyebrow="Inflación y renovación" title="Índice Nacional de Precios" />
    {query.guardado ? <Alert className="mt-7" variant="success">Nivel INPC guardado correctamente.</Alert> : null}
    {query.error ? <Alert className="mt-7" variant="danger">{query.error}</Alert> : null}

    <section className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(290px,.6fr)]">
      <div className="rounded-card border border-border bg-surface p-5 sm:p-6"><h2 className="font-serif text-2xl font-semibold tracking-tight text-ink sm:text-3xl">Registrar el INPC del mes</h2><p className="mt-3 text-sm text-ink-secondary">El nivel mensual es el dato que se conserva para calcular aumentos y renovaciones.</p>{suggestion ? <div className="mt-5 rounded-xl border border-brand/20 bg-brand-soft/40 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-ink">Sugerencia disponible</p><p className="mt-1 text-sm text-ink-secondary">INPC de {suggestion.month}: <span className="font-semibold text-ink">{suggestion.value}</span></p>{suggestion.annualPercent !== null ? <p className="mt-1 text-sm text-ink-secondary">Variación anual: <span className="font-semibold text-ink">{formatPercent(suggestion.annualPercent)}</span> <span className="text-xs">(validación CP151)</span></p> : null}</div><a className="rounded-lg border border-brand/30 bg-surface px-3 py-2 text-sm font-semibold text-brand hover:bg-bg" href={`/inflacion?mes=${suggestion.month}&valor=${suggestion.value}`}>Usar sugerencia</a></div></div> : <p className="mt-5 rounded-xl bg-bg p-4 text-sm text-ink-secondary">Sin sugerencia automática. Puedes registrar el nivel manualmente o configurar el token de Banxico.</p>}{canWrite ? <form action="/api/inflacion/indices" className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" method="post"><input name="indice" type="hidden" value="INPC" /><label className="text-xs font-medium text-ink-secondary">Mes<input className="mt-2 w-full rounded border border-border bg-surface px-3 py-2.5 text-sm text-ink" defaultValue={selectedMonth} name="mes" required type="month" /></label><label className="text-xs font-medium text-ink-secondary">Nivel oficial<input className="mt-2 w-full rounded border border-border bg-surface px-3 py-2.5 text-sm text-ink" defaultValue={query.valor ?? ""} inputMode="decimal" name="valor" placeholder="140.78000000" required /></label><label className="text-xs font-medium text-ink-secondary">Fecha de corte<input className="mt-2 w-full rounded border border-border bg-surface px-3 py-2.5 text-sm text-ink" defaultValue={`${selectedMonth}-10`} name="fechaCorte" required type="date" /></label><div className="flex items-end"><button className="w-full rounded bg-brand px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-hover" type="submit">Guardar nivel</button></div></form> : null}</div>
      <aside className="rounded-card border border-border bg-surface p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.13em] text-brand">Fuentes oficiales</p><h2 className="mt-1 font-serif text-xl font-semibold text-ink">Comprueba los datos</h2><p className="mt-2 text-sm text-ink-secondary">Los enlaces abren la consulta original del SIE de Banxico.</p><div className="mt-5 space-y-3"><a className="block rounded-xl border border-border p-4 text-sm transition hover:border-brand/40 hover:bg-bg" href={cp154Url} rel="noreferrer" target="_blank"><span className="font-semibold text-brand underline underline-offset-4">Nivel mensual del INPC (CP154) ↗</span><span className="mt-1 block text-xs text-ink-secondary">Fuente para el nivel que se guarda.</span></a><a className="block rounded-xl border border-border p-4 text-sm transition hover:border-brand/40 hover:bg-bg" href={cp151Url} rel="noreferrer" target="_blank"><span className="font-semibold text-brand underline underline-offset-4">Inflación mensual y anual (CP151) ↗</span><span className="mt-1 block text-xs text-ink-secondary">Referencia para validar la variación.</span></a></div></aside>
    </section>

    <section className="mt-7 rounded-card border border-border bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-serif text-2xl font-semibold tracking-tight text-ink sm:text-3xl">Seguimiento anual</h2><p className="mt-3 text-sm text-ink-secondary">El acumulado compara diciembre anterior contra el último nivel disponible.</p></div><div className="flex flex-wrap gap-2"><form><label className="sr-only" htmlFor="inflation-year">Año</label><input className="rounded border border-border bg-surface px-3 py-2 text-sm text-ink" defaultValue={year} id="inflation-year" max="2200" min="1900" name="anio" type="number" /><button className="ml-2 rounded border border-border bg-surface px-4 py-2 text-sm font-semibold text-ink hover:bg-bg">Consultar</button></form><a className="rounded bg-brand px-4 py-2 text-sm font-semibold text-white hover:bg-brand-hover" href={`/api/inflacion/reporte?anio=${year}`}>Exportar CSV</a></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-bg p-5"><p className="text-xs font-medium text-ink-secondary">Inflación acumulada {year}</p><p className="mt-2 text-3xl font-bold tracking-tight text-brand [font-variant-numeric:tabular-nums]">{report.acumulado === null ? "Incompleto" : formatPercent(report.acumulado * 100)}</p></div><div className="rounded-xl bg-bg p-5"><p className="text-xs font-medium text-ink-secondary">Avance de registros</p><p className="mt-2 text-3xl font-bold tracking-tight text-brand [font-variant-numeric:tabular-nums]">{report.meses.length}<span className="text-lg text-ink-secondary"> / 12</span></p></div></div></section>

    <section className="mt-7 overflow-hidden rounded-card border border-border bg-surface"><div className="border-b border-border px-5 py-4 sm:px-6"><h2 className="font-serif text-xl font-semibold text-ink">Historial registrado</h2><p className="mt-1 text-sm text-ink-secondary">Últimos niveles del INPC almacenados en el sistema.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-border text-xs font-semibold uppercase tracking-wide text-ink-secondary"><tr><th className="px-5 py-3 sm:px-6">Mes</th><th className="px-5 py-3">Índice</th><th className="px-5 py-3 text-right">Nivel oficial</th><th className="px-5 py-3 sm:px-6">Corte</th></tr></thead><tbody className="divide-y divide-border">{indices.length ? indices.map((item) => <tr className="hover:bg-bg/50" key={item.id}><td className="px-5 py-4 sm:px-6 font-semibold text-ink">{item.mes.toISOString().slice(0, 7)}</td><td className="px-5 py-4 text-ink-secondary">{item.indice}</td><td className="px-5 py-4 text-right font-semibold text-ink [font-variant-numeric:tabular-nums]">{item.valor.toString()}</td><td className="px-5 py-4 text-ink-secondary sm:px-6">{item.fechaCorte.toISOString().slice(0, 10)}</td></tr>) : <tr><td className="px-5 py-8 text-center text-sm text-ink-secondary" colSpan={4}>Aún no hay niveles INPC registrados.</td></tr>}</tbody></table></div></section>
  </>;
}
