import Link from "next/link";
import { notFound } from "next/navigation";
import { expireContractAction } from "@/app/_actions/foundation";
import { ReceiptBadge } from "@/components/collection/receipt-badge";
import { ConfirmSubmitButton } from "@/components/forms/confirm-submit-button";
import { Alert } from "@/components/ui/alert";
import { PageHeader } from "@/components/ui/page-header";
import { getSystemUser, WRITE_ROLES } from "@/lib/auth/authorization";
import { calculateReceiptPaymentBalance, calculateReceiptTotal, currentCollectionDate } from "@/lib/calculations/collection";
import { formatCurrency, formatDate } from "@/lib/format";
import { obtenerContrato } from "@/lib/services/foundation";

export default async function ContractDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ renovado?: string; error?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const [{ user }, contract] = await Promise.all([getSystemUser(), obtenerContrato(id)]);
  if (!contract) notFound();
  const canWrite = WRITE_ROLES.includes(user.rol as (typeof WRITE_ROLES)[number]);
  const today = currentCollectionDate();
  const renewalStart = new Date(contract.fechaFin); renewalStart.setUTCDate(renewalStart.getUTCDate() + 1);
  const renewalEnd = new Date(renewalStart); renewalEnd.setUTCFullYear(renewalEnd.getUTCFullYear() + 1); renewalEnd.setUTCDate(renewalEnd.getUTCDate() - 1);
  const renewalAvailable = today.getTime() >= contract.fechaFin.getTime();
  const receiptAccounts = contract.recibos.map((receipt) => {
    const total = calculateReceiptTotal({ rent: Number(receipt.monto), servicesCharge: Number(receipt.cargoFijo) });
    return { receipt, total, ...calculateReceiptPaymentBalance({ total, payments: receipt.pagos.map((payment) => ({ amount: Number(payment.monto) })) }) };
  });
  const unpaidReceipts = receiptAccounts.filter((account) => account.saldoPendiente > 0);
  const paidReceipts = receiptAccounts.filter((account) => account.saldoPendiente === 0);
  const pendingTotal = unpaidReceipts.reduce((sum, account) => sum + account.saldoPendiente, 0);
  const daysRemaining = Math.max(0, Math.ceil((contract.fechaFin.getTime() - today.getTime()) / 86_400_000));
  const guaranteeLabel = contract.tipoGarantia === "AVAL" ? "Aval" : contract.tipoGarantia === "PRENDA" ? "Prenda" : "Inmueble";

  return <>
    <PageHeader action={canWrite ? <Link className="cursor-pointer rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-hover" href={`/contratos/${id}/editar`}>Editar contrato</Link> : null} description={`${contract.unidad.propiedad.direccion} · Unidad ${contract.unidad.identificador}`} eyebrow="Contrato vigente" title={contract.arrendatario} />
    {query.renovado ? <Alert className="mt-7" variant="success">Contrato renovado y ajuste INPC registrado.</Alert> : null}{query.error ? <Alert className="mt-7" variant="danger">{query.error}</Alert> : null}

    <section className="mt-7 rounded-3xl bg-brand p-6 text-white shadow-[7px_7px_15px_#c6cdd6,-7px_-7px_15px_#fff]"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-white/65">Estado de cuenta</p><p className="mt-2 font-serif text-3xl font-semibold">{unpaidReceipts.length ? `${unpaidReceipts.length} pago${unpaidReceipts.length === 1 ? " pendiente" : "s pendientes"}` : "Pagos al corriente"}</p><p className="mt-2 text-sm text-white/75">Vence el {formatDate(contract.fechaFin)} · {daysRemaining} días restantes de vigencia</p></div><div className="flex flex-wrap gap-3"><Link className="cursor-pointer rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-brand hover:bg-white/90" href="/cobranza">Gestionar pagos</Link><Link className="cursor-pointer rounded-xl border border-white/35 px-4 py-2.5 text-sm font-bold text-white hover:bg-white/10" href={`/propiedades/${contract.unidad.propiedadId}/unidades/${contract.unidadId}`}>Ver unidad</Link></div></div></section>

    <section aria-label="Resumen financiero" className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Renta mensual", formatCurrency(contract.rentaMensualBase), "text-brand"], ["Pendiente por cobrar", formatCurrency(pendingTotal), unpaidReceipts.length ? "text-danger" : "text-success"], ["Recibos pagados", `${paidReceipts.length} de ${contract.recibos.length}`, "text-ink"], ["Día habitual de pago", `Día ${contract.diaPago}`, "text-ink"]].map(([label, value, color]) => <div className="rounded-2xl bg-bg p-5 shadow-[5px_5px_12px_#c6cdd6,-5px_-5px_12px_#fff]" key={label}><p className="text-xs font-bold uppercase tracking-[.1em] text-ink-secondary">{label}</p><p className={`mt-2 text-xl font-bold [font-variant-numeric:tabular-nums] ${color}`}>{value}</p></div>)}</section>

    <section className="mt-8"><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-brand/70">Operación</p><h2 className="mt-1 font-serif text-2xl font-semibold text-ink">Historial de pagos</h2><p className="mt-1 text-sm text-ink-secondary">Recibos generados para este contrato.</p></div><Link className="text-sm font-semibold text-brand hover:text-brand-hover" href="/cobranza">Abrir cobranza</Link></div>{contract.recibos.length === 0 ? <Alert variant="info">Todavía no hay recibos generados para este contrato.</Alert> : <div className="overflow-x-auto rounded-3xl bg-bg shadow-[7px_7px_15px_#c6cdd6,-7px_-7px_15px_#fff]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-brand/10 text-[10px] font-bold uppercase tracking-[.1em] text-ink-secondary"><tr><th className="px-6 py-4">Periodo</th><th className="px-6 py-4">Vencimiento</th><th className="px-6 py-4">Estatus</th><th className="px-6 py-4">Pagado / saldo</th><th className="px-6 py-4 text-right">Total</th></tr></thead><tbody className="divide-y divide-brand/10">{receiptAccounts.map(({ receipt, total, montoPagado, saldoPendiente }) => <tr className="hover:bg-white/35" key={receipt.id}><td className="px-6 py-5 font-semibold text-ink">{formatDate(receipt.periodo)}</td><td className="px-6 py-5 text-ink-secondary">{formatDate(receipt.fechaVencimiento)}</td><td className="px-6 py-5"><ReceiptBadge status={receipt.estatus} /></td><td className="px-6 py-5 text-ink-secondary"><span className="font-semibold text-ink">{formatCurrency(montoPagado)}</span><span className={saldoPendiente > 0 ? "ml-2 text-danger" : "ml-2 text-success"}>Saldo {formatCurrency(saldoPendiente)}</span></td><td className="px-6 py-5 text-right font-bold text-ink [font-variant-numeric:tabular-nums]">{formatCurrency(total)}</td></tr>)}</tbody></table></div>}</section>

    <section className="mt-8 grid gap-6 xl:grid-cols-2"><div className="rounded-3xl bg-bg p-6 shadow-[7px_7px_15px_#c6cdd6,-7px_-7px_15px_#fff]"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-brand/70">Vigencia</p><h2 className="mt-1 font-serif text-xl font-semibold text-ink">Términos del contrato</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[["Inicio", formatDate(contract.fechaInicio)], ["Finalización", formatDate(contract.fechaFin)], ["Plazo", `${contract.plazoMeses} meses`], ["Depósito", formatCurrency(contract.depositoGarantia)], ["Servicios mensuales (incluye agua)", formatCurrency(contract.cargoFijoMensual)], ["Estado", contract.estado === "ACTIVO" ? "Activo" : "Vencido"]].map(([label, value]) => <div key={label}><dt className="text-xs font-medium text-ink-secondary">{label}</dt><dd className="mt-1 text-sm font-bold text-ink [font-variant-numeric:tabular-nums]">{value}</dd></div>)}</dl></div><div className="rounded-3xl bg-bg p-6 shadow-[7px_7px_15px_#c6cdd6,-7px_-7px_15px_#fff]"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-brand/70">Expediente</p><h2 className="mt-1 font-serif text-xl font-semibold text-ink">Contacto y garantía</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[["Correo", contract.emailArrendatario || "No registrado"], ["Teléfono", contract.telefonoArrendatario || "No registrado"], ["Garantía", guaranteeLabel], ["Responsable", contract.aval], ...(contract.valorGarantia ? [["Valor de garantía", formatCurrency(contract.valorGarantia)]] : [])].map(([label, value]) => <div key={label}><dt className="text-xs font-medium text-ink-secondary">{label}</dt><dd className="mt-1 break-words text-sm font-bold text-ink">{value}</dd></div>)}</dl></div></section>

    {contract.ajustesInflacion.length > 0 ? <section className="mt-8 rounded-3xl bg-bg p-6 shadow-[7px_7px_15px_#c6cdd6,-7px_-7px_15px_#fff]"><h2 className="font-serif text-xl font-semibold text-ink">Historial de ajustes</h2><div className="mt-4 space-y-3">{contract.ajustesInflacion.map((adjustment) => <div className="flex flex-wrap justify-between gap-3 border-t border-brand/10 pt-3 text-sm" key={adjustment.id}><span className="text-ink-secondary">{adjustment.indiceUsado}</span><span className="font-semibold text-ink [font-variant-numeric:tabular-nums]">{formatCurrency(adjustment.rentaResultante)}</span></div>)}</div></section> : null}
    {canWrite && contract.estado === "ACTIVO" && !renewalAvailable ? <Alert className="mt-7" variant="info">La renovación estará disponible a partir del {formatDate(contract.fechaFin)}.</Alert> : null}
    {canWrite && contract.estado === "ACTIVO" && renewalAvailable ? <section className="mt-7 rounded-card border border-border bg-surface p-5"><h2 className="text-sm font-semibold text-ink">Renovar con INPC</h2><p className="mt-2 text-sm text-ink-secondary">Se creará un contrato nuevo y este contrato conservará intacto su historial.</p><form action={`/api/contratos/${id}/renovar`} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3" method="post"><input name="indice" type="hidden" value="INPC" /><label className="text-xs font-medium text-ink-secondary">Mes base<input className="mt-2 w-full rounded border border-border px-3 py-2.5 text-sm" defaultValue={new Date(Date.UTC(contract.fechaFin.getUTCFullYear() - 1, contract.fechaFin.getUTCMonth(), 1)).toISOString().slice(0, 7)} name="mesBase" required type="month" /></label><label className="text-xs font-medium text-ink-secondary">Mes final<input className="mt-2 w-full rounded border border-border px-3 py-2.5 text-sm" defaultValue={contract.fechaFin.toISOString().slice(0, 7)} name="mesFinal" required type="month" /></label><label className="text-xs font-medium text-ink-secondary">Nuevo plazo<input className="mt-2 w-full rounded border border-border px-3 py-2.5 text-sm" defaultValue="12" min="1" name="plazoMeses" required type="number" /></label><label className="text-xs font-medium text-ink-secondary">Inicio<input className="mt-2 w-full rounded border border-border px-3 py-2.5 text-sm" defaultValue={renewalStart.toISOString().slice(0, 10)} name="fechaInicio" required type="date" /></label><label className="text-xs font-medium text-ink-secondary">Finalización<input className="mt-2 w-full rounded border border-border px-3 py-2.5 text-sm" defaultValue={renewalEnd.toISOString().slice(0, 10)} name="fechaFin" required type="date" /></label><div className="flex items-end"><ConfirmSubmitButton message="¿Crear el contrato renovado con la renta calculada por INPC?">Renovar contrato</ConfirmSubmitButton></div></form></section> : null}
    {canWrite && contract.estado === "ACTIVO" ? <section className="mt-8 border-t border-border pt-5"><form action={expireContractAction.bind(null, id)}><ConfirmSubmitButton message="¿Marcar este contrato como vencido? El historial se conservará.">Marcar contrato como vencido</ConfirmSubmitButton></form></section> : null}
  </>;
}
